language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install -r requirements-docs.txt
script:
  - py.test --cov=wrfpy --cov-report term --cov-report xml:cov.sml tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
